vich_uploader:
    db_driver: orm

    mappings:
        metal_maiden_portrait:
            uri_prefix: /images/metal_maiden/portrait
            upload_destination: '%kernel.project_dir%/public/images/metal_maiden/portrait'

            inject_on_load: true # should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File
            delete_on_update: true # should the file be deleted when a new file is uploaded ;
            delete_on_remove: true # should the file be deleted when the entity is removed ;
            
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'attireSlug'}

        nation:
            uri_prefix: /images/nation
            upload_destination: '%kernel.project_dir%/public/images/nation'

            inject_on_load: false # should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File
            delete_on_update: true # should the file be deleted when a new file is uploaded ;
            delete_on_remove: true # should the file be deleted when the entity is removed ;
            
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'nameSlug'}