#index:
#    path: /
#    controller: App\Controller\DefaultController::index


homepage:
    # path: /
    # controller: App\Controller\MetalMaidenController::index
    path: /{_locale}
    controller: App\Controller\MetalMaidenController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        # template: default/homepage.html.twig
        _locale: '%locale%'
