<?php

namespace App\DataFixtures;

use App\DataFixtures\AttireCategoryFixtures;
use App\Entity\AttireCategory;
use App\Entity\MetalMaiden;
use App\Entity\Nation;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

class MetalMaidenFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $this->loadMetalMaidens($manager);
    }

    public function getDependencies()
    {
        return array(
            AttireCategoryFixtures::class,
        );
    }

    private function loadMetalMaidens(ObjectManager $manager)
    {
    	$i = 0;

        foreach ($this->getMetalMaidenData() as [$name, $attire, $attireCategoryAbbreviation, $nationName]) {
            $metalMaiden = new MetalMaiden();
            $metalMaiden->setName($name);
            $metalMaiden->setAttire($attire);
            $metalMaiden->setAttireCategory($this->getReference('attire_category-' . $attireCategoryAbbreviation));
            $metalMaiden->setNation($this->getReference('nation-' . $nationName));

            $manager->persist($metalMaiden);
            $this->addReference('metal_maiden-' . $i++, $metalMaiden);
        }

        $manager->flush();
    }

    private function getMetalMaidenData(): array
    {
        return [
            // $metalMaidenData = [$name, $attire, $attireCategoryAbbreviation, $nationName];
            ['Lyudmila · Levichenko', '2B1 Oka SPA', 'SPG', 'Rossiya'],
            ['Videniya Schaefer', '35(t) Light Tank', 'LT', 'Bavaria'],
            ['Maya Klein', '38 (T) Tank Ausf. G', 'LT', 'Bavaria'],
            ['Stelaya Koch', '38(t) Light Tank', 'LT', 'Bavaria'],
            ['Lana Svoboda', '38(t) Tank Ausf. D', 'LT', 'Bavaria'],
            ['Yagisaka Maki', '75 Type 130mm Multiple Rocket Launcher', 'SPG', 'Fusang'],
            ['Rowena Kingsley', 'A17 Prototype', 'LT', 'Britannia'],
            ['Katia Hoyle', 'A33 Excelsior', 'HT', 'Britannia'],
            ['Leanne Flosen', 'A34 Comet', 'MT', 'Britannia'],
            ['Cecilia Field', 'A42 Churchill (Mk-VII)', 'HT', 'Britannia'],
            ['Celia Durand', 'AMX Mk F3 SP Gun', 'SPG', 'Gallia'],
            ['Peggy Blake', 'AMX-105-AM SPA', 'SPG', 'Gallia'],
            ['Caitlin Pobil', 'AMX-13 (75mm)', 'LT', 'Gallia'],
            ['Anouk Lavoisier', 'AMX-13 (90mm)', 'LT', 'Gallia'],
            ['Anna Tassigny', 'AMX-13 Diesel', 'LT', 'Gallia'],
            ['Penny Juin', 'AMX-50', 'HT', 'Gallia'],
            ['Amanda · Lefebble', 'AMX-M449', 'HT', 'Gallia'],
            ['Lydia Muffat', 'AMX40 Light Tank', 'LT', 'Gallia'],
            ['Natalie Leclair', 'ARL44 Heavy Tank', 'HT', 'Gallia'],
            ['Nadezhda Yermakovna', 'ASU-57 Airborne Tank Destroyer', 'ATG', 'Rossiya'],
            ['Lonny Shurochkana', 'ASU-85', 'ATG', 'Rossiya'],
            ['Loris Doris', 'AT2 Anti-tank SPG', 'ATG', 'Britannia'],
            ['Ophelia Brook', 'AT8 Anti-tank SPG', 'ATG', 'Britannia'],
            ['Esther Wilton', 'Achilles SPATG', 'LAV', 'Britannia'],
            ['Pam Hunterdon', 'Alecto Mk-I', 'ATG', 'Britannia'],
            ['Claire Owen', 'Alecto Mk-II', 'ATG', 'Britannia'],
            ['Corona Houston', 'Alecto Mk-IV', 'ATG', 'Britannia'],
            ['Jasmine Neil', 'Archer', 'ATG', 'Britannia'],
            ['Mansa Semenovna', 'BA-10M', 'LAV', 'Rossiya'],
            ['Irina Mikhyevna', 'BA-3', 'LAV', 'Rossiya'],
            ['Lyubov Savelyevna', 'BA-6', 'LAV', 'Rossiya'],
            ['Katyusa Yakovlevna', 'BM21 Multiple Rocket Launcher', 'SPG', 'Rossiya'],
            ['Mashuya Vyazeskaya', 'BMP-1 Infantry Fighting Vehicle', 'LAV', 'Rossiya'],
            ['Katerina Flyorova', 'BT-2 Fast Tank', 'LT', 'Rossiya'],
            ['Clara Chaykina', 'BT-3 Fast Tank', 'LT', 'Rossiya'],
            ['Ruza Boltonogova', 'BT-4 Fast Tank', 'LT', 'Rossiya'],
            ['Tessa Nieminen', 'BT-42', 'LT', 'Bavaria'],
            ['Lena Tolubka', 'BT-5 Fast Tank', 'LT', 'Rossiya'],
            ['Suzanne Petrova', 'BT-7 Fast Tank', 'LT', 'Rossiya'],
            ['Alia Polivanova', 'BT-7M Tank', 'LT', 'Rossiya'],
            ['Slava Peskov', 'BTR-141', 'LAV', 'Rossiya'],
            ['Kyra Vasilevskaya', 'BTR-40', 'LAV', 'Rossiya'],
            ['Anastasia Aleksandrovna', 'BTR-50', 'LAV', 'Rossiya'],
            ['Slava Gelman', 'BTR-50PA', 'LAV', 'Rossiya'],
            ['Heidi Hendzel', 'Bandkanon 1A-155', 'SPG', 'Sweden'],
            ['Zahna Hughes', 'Birch SPG', 'SPG', 'Britannia'],
            ['Bobbi Christian', 'Bison II', 'SPG', 'Bavaria'],
            ['Prima Scholz', 'Bison SPG', 'SPG', 'Bavaria'],
            ['Wendy Barker', 'Black Prince', 'HT', 'Britannia'],
            ['Para Werner', 'Brummbär', 'ATG', 'Bavaria'],
            ['Tiffany Martin', 'Centaur Medium Tank', 'MT', 'Britannia'],
            ['Tia Windsor', 'Centurion Mk-I', 'MT', 'Britannia'],
            ['Victoria Wellington', 'Centurion Mk-III', 'HT', 'Britannia'],
            ['Edith Salet', 'Chatillon 25t', 'MT', 'Gallia'],
            ['Audrey Autumn', 'Churblade II', 'HT', 'Britannia'],
            ['Isabel Churchill', 'Churchill AVRE', 'HT', 'Britannia'],
            ['Camilla Beck', 'Churchill Mk-I', 'HT', 'Britannia'],
            ['Ethel Hall', 'Churchill Mk-II', 'HT', 'Britannia'],
            ['Emma Carter', 'Churchill Mk-III', 'HT', 'Britannia'],
            ['Daphne Miller', 'Churchill Mk-IV', 'HT', 'Britannia'],
            ['Shirley Green', 'Churchill Mk-V', 'HT', 'Britannia'],
            ['Merry Churchill', 'Churchill Mk-VI', 'HT', 'Britannia'],
            ['Mandy Brook', 'Churchill Mk-VIII', 'HT', 'Britannia'],
            ['Rachel Watson', 'Conqueror', 'HT', 'Britannia'],
            ['Teresa Bull', 'Covenanter Cruiser Tank', 'LT', 'Britannia'],
            ['Darlene Macarthy', 'Cromwell Mk-I', 'MT', 'Britannia'],
            ['Philia Chapman', 'Cromwell Mk-III', 'MT', 'Britannia'],
            ['Deborah Payne', 'Cromwell Mk-IV', 'MT', 'Britannia'],
            ['Florence O\'Neil', 'Cromwell Mk-VI', 'MT', 'Britannia'],
            ['Denise Auchinleck', 'Cromwell Mk-VII', 'MT', 'Britannia'],
            ['Grace Montgomery', 'Crusader Mk-I', 'LT', 'Britannia'],
            ['Hanni Stoker', 'Crusader Mk-II', 'LT', 'Britannia'],
            ['Jennifer Fox', 'Crusader Mk-III', 'LT', 'Britannia'],
            ['Lilith Bernard', 'Crusader SPG', 'SPG', 'Britannia'],
            ['Karen Jonathan', 'Daimler Armored Car', 'LAV', 'Britannia'],
            ['Portia Porsche', 'Elefant Tank Destroyer', 'ATG', 'Bavaria'],
            ['Alexa Luis', 'FCM F1', 'HT', 'Gallia'],
            ['Arezzo, No. 041', 'FFV304MK2 Fox', 'HT', 'National Flag-11'],
            ['Carolina Hamilton', 'FV201 Heavy Tank', 'HT', 'Britannia'],
            ['Joanna Wilson', 'FV304', 'SPG', 'Britannia'],
            ['Christine Jones', 'FV4004', 'ATG', 'Britannia'],
            ['Keira · Richardson', 'FV4005', 'ATG', 'Britannia'],
            ['Fatima Ayoubi', 'FV601 Saladin', 'LAV', 'Britannia'],
            ['Yula Porsche', 'Ferdinand Prototype', 'ATG', 'Bavaria'],
            ['', 'General Executioner Mark-33', 'ATG', 'Stardust Farer'],
            ['Dorothy Kunnich', 'Geschützwagen Tiger 17', 'SPG', 'Bavaria'],
            ['Jerrie Bill', 'Grant Mk-I', 'MT', 'Freedonia'],
            ['Laina Evans', 'Grant Mk-II', 'MT', 'Freedonia'],
            ['Demi Franklin', 'Grant Mk-III', 'MT', 'Freedonia'],
            ['Natalie Brant', 'Grant Mk-IV', 'MT', 'Freedonia'],
            ['Valerie Ericsson', 'Grant Mk-V', 'MT', 'Freedonia'],
            ['Monica Colin', 'Grant Mk-VI', 'MT', 'Freedonia'],
            ['Chelly Marshall', 'Grant Mk-VII', 'MT', 'Freedonia'],
            ['Kyleigh Kruger', 'Grant Mk-VIII', 'MT', 'Freedonia'],
            ['Ada Jan', 'Grille H', 'SPG', 'Bavaria'],
            ['Dorothy Kunnich', 'Grille M', 'SPG', 'Bavaria'],
            ['Evelyn Friedrich', 'Hetzer', 'ATG', 'Bavaria'],
            ['Jenny Khloe', 'Hummel SPG', 'SPG', 'Bavaria'],
            ['Jenny Khloe', 'Hummel(Late)', 'SPG', 'Bavaria'],
            ['Hunt Uang G', 'Hunt Uang G', 'ATG', 'National Flag-11'],
            ['Marina Mikhailov', 'IS-1', 'HT', 'Rossiya'],
            ['Mirava Yagudina', 'IS-2', 'HT', 'Rossiya'],
            ['Sophia Malinovskaya', 'IS-2m', 'HT', 'Rossiya'],
            ['Sarah Sholokhovna', 'IS-3', 'HT', 'Rossiya'],
            ['Xenia Ivaneva', 'IS-4 Heavy Tank', 'HT', 'Rossiya'],
            ['Victoria Vasilieva', 'IS-7 Heavy Tank', 'HT', 'Rossiya'],
            ['Viola Fateyeva', 'ISU-122', 'ATG', 'Rossiya'],
            ['Ilona Hanks', 'Jagdpanther', 'ATG', 'Bavaria'],
            ['Cornelia Krum', 'Jagdpanther (12.8cm)', 'ATG', 'Bavaria'],
            ['Haya Schulz', 'Jagdpanzer IV', 'ATG', 'Bavaria'],
            ['Norena Bolter', 'Jagdpanzer IV Alkett', 'ATG', 'Bavaria'],
            ['Rinoa Webb', 'Jagdpanzer IV Prototype', 'ATG', 'Bavaria'],
            ['Nelly Wagner', 'Jagdtiger', 'ATG', 'Bavaria'],
            ['Nelly Wagner', 'Jagdtiger (88mm)', 'ATG', 'Bavaria'],
            ['Chen Xi', 'KFMLRS', 'SPG', 'China'],
            ['Valentina Leontiyevna', 'KV-1', 'HT', 'Rossiya'],
            ['Galina Svyatoslavna', 'KV-1B', 'HT', 'Rossiya'],
            ['Galina Svyatoslavna', 'KV-1K', 'SPG', 'Rossiya'],
            ['Valeria Simonovna', 'KV-1S', 'HT', 'Rossiya'],
            ['Aurora Molotova', 'KV-2', 'HT', 'Rossiya'],
            ['Vera Chekovna', 'KV-3', 'HT', 'Rossiya'],
            ['Matova Voroshilovna', 'KV-4', 'HT', 'Rossiya'],
            ['Kronoja Ivanovna', 'KV-5', 'HT', 'Rossiya'],
            ['Zoya Zhukova', 'KV-85', 'HT', 'Rossiya'],
            ['Katyusa Yakovlevna', 'Katyusha M13', 'SPG', 'Rossiya'],
            ['Julia Sidorovna', 'Katyusha M8', 'SPG', 'Rossiya'],
            ['Lambda', 'Lambda', 'LAV', 'Stardust Farer'],
            ['Carla Bayer', 'Leopard 1 Tank', 'MT', 'Bavaria'],
            ['Audrey Estella', 'Lorin 155 Self-Propelled Artillery', 'SPG', 'Gallia'],
            ['Diane Stiegler', 'Luchs', 'LAV', 'Bavaria'],
            ['Lesley Davis', 'M10 Wolverine', 'LAV', 'Freedonia'],
            ['Dia Foster', 'M103 Heavy Tank', 'HT', 'Freedonia'],
            ['Rosalyn Campbell', 'M103A2 Heavy Tank', 'HT', 'Freedonia'],
            ['Laura Adrian', 'M10A1 Wolverine', 'LAV', 'Freedonia'],
            ['Arielle Isaac', 'M12 SPG', 'SPG', 'Freedonia'],
            ['Daphne Davis', 'M18 Hellcat', 'LAV', 'Freedonia'],
            ['Mary-Ann Adams', 'M2 Half Track', 'LAV', 'Freedonia'],
            ['Angelina James', 'M2 Light Tank', 'LT', 'Freedonia'],
            ['Virginia Andy', 'M2 Medium Tank', 'MT', 'Freedonia'],
            ['Edna Laurens', 'M22 Locust', 'LT', 'Freedonia'],
            ['Cecile Chaffee', 'M24 Chaffee', 'LT', 'Freedonia'],
            ['Helena Pershing', 'M26 Pershing', 'MT', 'Freedonia'],
            ['Hunny Hobbs', 'M3 Half-track', 'LAV', 'Freedonia'],
            ['Yolanda Robertson', 'M3 Scout Car', 'LAV', 'Freedonia'],
            ['Cersei Green', 'M3 Stuart', 'LT', 'Freedonia'],
            ['Jenna Jackson', 'M36 Jackson', 'LAV', 'Freedonia'],
            ['Kewell Roberts', 'M37 SPG', 'SPG', 'Freedonia'],
            ['Caroline Halsey', 'M3A1 Stuart', 'LT', 'Freedonia'],
            ['Willa Bell', 'M3A3 Stuart', 'LT', 'Freedonia'],
            ['Valerina Hill', 'M4 Composite', 'MT', 'Freedonia'],
            ['Rita James', 'M40 SPG', 'SPG', 'Freedonia'],
            ['Daisy Chester', 'M41 Bulldog', 'LT', 'Freedonia'],
            ['Gretchen Spike', 'M41A1 Bulldog', 'LT', 'Freedonia'],
            ['Daisy Chester', 'M41GTI light tank', 'LT', 'Bavaria'],
            ['Serena MacArthur', 'M43 SPG', 'SPG', 'Freedonia'],
            ['Nina McNair', 'M44 SPG', 'SPG', 'Freedonia'],
            ['Aleda Patton', 'M48A2 Patton', 'MT', 'Freedonia'],
            ['Ruan (surname), Jin yan', 'M48A3 (Gift Type)', 'MT', 'China'],
            ['Eugene Justina', 'M48A3K', 'MT', 'National Flag-08'],
            ['Ice Jo', 'M5 Stuart', 'LT', 'Freedonia'],
            ['Cecile Chaffee', 'M551 Light Tank', 'LT', 'Freedonia'],
            ['Yuna Brown', 'M56 Scorpion', 'ATG', 'Freedonia'],
            ['Freda Leonard', 'M5A1 Stuart', 'LT', 'Freedonia'],
            ['Lisanna Lewish', 'M6 Heavy Tank', 'HT', 'Freedonia'],
            ['Lasia Cruz', 'M6A1 Heavy Tank', 'HT', 'Freedonia'],
            ['Vashti Bradley', 'M6A2 Heavy Tank', 'HT', 'Freedonia'],
            ['Nia · Jax', 'M6A2E1 HT', 'HT', 'Freedonia'],
            ['Melia Mars', 'M7 Medium Tank', 'MT', 'Freedonia'],
            ['Vilna Markus', 'M7 Priest', 'SPG', 'Freedonia'],
            ['Sarah Phebe', 'M7B1 Priest', 'SPG', 'Freedonia'],
            ['Eno Zamperini', 'M7B2 Priest', 'SPG', 'Freedonia'],
            ['Betsy Hamill', 'M8 Howitzer', 'SPG', 'Freedonia'],
            ['Raisa Stalina', 'MS-1', 'LT', 'Rossiya'],
            ['Jocelyn Bowen', 'Marder II', 'ATG', 'Bavaria'],
            ['Dora Schroder', 'Marder II (Type 132)', 'ATG', 'Bavaria'],
            ['Kseniya Smallman', 'Marder III (Type 139)', 'ATG', 'Bavaria'],
            ['Sharan Ruud', 'Marder III Ausf. M', 'ATG', 'Bavaria'],
            ['Gala Wolf', 'Marder Tank-destroyer', 'ATG', 'Bavaria'],
            ['', 'Mark IV Tank', 'HT', 'Britannia'],
            ['Gina Matthews', 'Matilda', 'MT', 'Britannia'],
            ['Vivian Bennett', 'Matilda (A11)', 'MT', 'Britannia'],
            ['Shelby Sakna', 'Matilda CS', 'MT', 'Britannia'],
            ['Dido Price', 'Matilda Hedgehog', 'SPG', 'Britannia'],
            ['Heather Bacon', 'Matilda Mk-III', 'MT', 'Britannia'],
            ['Epsilon', 'Mini Epsilon (Capture Type)', 'LT', 'Stardust Farer'],
            ['Agatha Byron', 'Mk.II Cruiser Tank', 'LT', 'Britannia'],
            ['Igraine Dalton', 'Mk.III Cruiser Tank', 'LT', 'Britannia'],
            ['Elisa Hawke', 'Mk.IV Cruiser Tank', 'LT', 'Britannia'],
            ['Felicia Urquhart', 'Mk.VIII Light Tank', 'LT', 'Britannia'],
            ['Hedwig Obos', 'Nashorn ATG', 'ATG', 'Bavaria'],
            ['Ignacia Yevgeniya', 'Object 212 SPG', 'SPG', 'Rossiya'],
            ['Vika Agrippina', 'Object 262 SPG', 'SPG', 'Rossiya'],
            ['Mocha Meretskova', 'Object 263 Anti-tank Gun', 'ATG', 'Rossiya'],
            ['Luigina Pascucci', 'P 26/40', 'HT', 'Stivalia'],
            ['Materina Viye', 'Panhard 178A', 'LAV', 'Gallia'],
            ['Sunny Marceau', 'Panhard 178B', 'LAV', 'Gallia'],
            ['Ida Brooke', 'Panther Ausf. A', 'MT', 'Bavaria'],
            ['Mila Hann', 'Panther Ausf. D', 'MT', 'Bavaria'],
            ['Lena Ballod', 'Panther Ausf. F', 'MT', 'Bavaria'],
            ['Michelle Farmiga', 'Panther Ausf. G', 'MT', 'Bavaria'],
            ['Carla Bayer', 'Panther Prototype', 'MT', 'Bavaria'],
            ['Nina Streep', 'Panzer II Ausf. F (Late)', 'LT', 'Bavaria'],
            ['Claudia Windini', 'Panzer III Ausf. E', 'MT', 'Bavaria'],
            ['Ruth Martina', 'Panzer III Ausf. F', 'MT', 'Bavaria'],
            ['Petra Melantha', 'Panzer III Ausf. G', 'MT', 'Bavaria'],
            ['Yulia Andreas', 'Panzer III Ausf. H', 'MT', 'Bavaria'],
            ['Fiona Fogel', 'Panzer III Ausf. J', 'MT', 'Bavaria'],
            ['Veronica Wolf', 'Panzer III Ausf. L', 'MT', 'Bavaria'],
            ['Lumina Gross', 'Panzer III Ausf. M', 'MT', 'Bavaria'],
            ['Sabina Viroka', 'Panzer III Prototype', 'MT', 'Bavaria'],
            ['Karolina Benjamin', 'Panzer IV Ausf. A', 'MT', 'Bavaria'],
            ['Vanda Nicolas', 'Panzer IV Ausf. B', 'MT', 'Bavaria'],
            ['Amelia Lorenz', 'Panzer IV Ausf. C', 'MT', 'Bavaria'],
            ['Estelle Quint', 'Panzer IV Ausf. D', 'MT', 'Bavaria'],
            ['Seurat Franke', 'Panzer IV Ausf. E', 'MT', 'Bavaria'],
            ['Kathy Winkler', 'Panzer IV Ausf. F2', 'MT', 'Bavaria'],
            ['Rebecca Wagner', 'Panzer IV Ausf. G', 'MT', 'Bavaria'],
            ['Celine Hyon', 'Panzer IV Ausf. H', 'MT', 'Bavaria'],
            ['', 'Panzer IV Ausf. J', 'MT', 'Bavaria'],
            ['Rebecca Wagner', 'Panzer IV Ausf.G (H)', 'MT', 'Bavaria'],
            ['Vanessa Finn', 'Panzer IV Prototype', 'MT', 'Bavaria'],
            ['Mirian Jaujard', 'Pz.Kpfw.B2', 'HT', 'Bavaria'],
            ['Eleanore Goldman', 'Renault B1 Heavy Tank', 'HT', 'Gallia'],
            ['Lorraine Lawrence', 'Renault B1 bis', 'HT', 'Gallia'],
            ['Edith Felicity', 'Renault FT-17', 'LT', 'Gallia'],
            ['Jacqueline Bourgeois', 'Renault R35', 'LT', 'Gallia'],
            ['Pietella Bullitt', 'SEM90/53', 'ATG', 'Stivalia'],
            ['Sonia Law', 'SP I.C.', 'LT', 'Bavaria'],
            ['Darya Govorova', 'SU-100', 'ATG', 'Rossiya'],
            ['Dahlia Mustafina', 'SU-100Y Self-Propelled Gun', 'ATG', 'Rossiya'],
            ['Anfissa Valeriyevna', 'SU-122', 'ATG', 'Rossiya'],
            ['Janina Smonikova', 'SU-14 SPG', 'SPG', 'Rossiya'],
            ['Martisha Dubiyeva', 'SU-18 SPG', 'SPG', 'Rossiya'],
            ['Vasilisa Ehrenburg', 'SU-26 SPG', 'SPG', 'Rossiya'],
            ['Mocha Meretskova', 'SU-5 SPG', 'SPG', 'Rossiya'],
            ['Alida Andreyevna', 'SU-76', 'ATG', 'Rossiya'],
            ['Lena Arkhipovna', 'SU-76I', 'ATG', 'Rossiya'],
            ['Violeta Sergeva', 'SU-76M', 'ATG', 'Rossiya'],
            ['Mocha Meretskova', 'SU-8 SPG', 'SPG', 'Rossiya'],
            ['Marucha Dmitrievna', 'SU-85', 'ATG', 'Rossiya'],
            ['Lenny Heymann', 'Sd.Kfz.231', 'LAV', 'Bavaria'],
            ['Jutta Heymann', 'Sd.Kfz.232', 'LAV', 'Bavaria'],
            ['Frieda Miller', 'Sd.Kfz.233', 'LAV', 'Bavaria'],
            ['Catherine Schmidt', 'Sd.Kfz.234/1', 'LAV', 'Bavaria'],
            ['Belinda Luis', 'Sd.Kfz.234/2', 'LAV', 'Bavaria'],
            ['Leoni Alan', 'Sd.Kfz.234/3', 'LAV', 'Bavaria'],
            ['Sofie Paulus', 'Sd.Kfz.251/1', 'LAV', 'Bavaria'],
            ['Patti Paulson', 'Sd.Kfz.251/10', 'LAV', 'Bavaria'],
            ['Larah Sean', 'Sd.Kfz.251/22', 'LAV', 'Bavaria'],
            ['Alicia Jonas', 'Sd.Kfz.251/23', 'LAV', 'Bavaria'],
            ['Lilina Luca', 'Sd.Kfz.251/9', 'LAV', 'Bavaria'],
            ['Louisa Washington', 'Sexton SPG', 'SPG', 'Britannia'],
            ['Penny Sherman', 'Sherman Firefly', 'MT', 'Britannia'],
            ['Greta White', 'Sherman Mk-I', 'MT', 'Freedonia'],
            ['Scully Harris', 'Sherman Mk-II', 'MT', 'Freedonia'],
            ['Easter Clark', 'Sherman Mk-III', 'MT', 'Freedonia'],
            ['Zoe Sherman', 'Sherman Mk-IV', 'MT', 'Freedonia'],
            ['Zoe Sherman', 'Sherman Mk-V', 'MT', 'Freedonia'],
            ['Miranda · Lopez', 'Soma S-35 Medium Tank', 'MT', 'Gallia'],
            ['Alizée Monet', 'Soma S-40 MT', 'MT', 'Gallia'],
            ['Ines Garcia', 'Staghound Mk-III', 'LAV', 'Freedonia'],
            ['', 'Steyr WT', 'ATG', 'Bavaria'],
            ['Ingrid Lindbergh', 'Strv.74', 'LAV', 'Sweden'],
            ['Mary Rahr', 'Sturer Emil', 'ATG', 'Bavaria'],
            ['Jessica Conrad', 'Sturmgeschütz III Ausf. A', 'ATG', 'Bavaria'],
            ['Muse Rudolf', 'Sturmgeschütz III Ausf. B', 'ATG', 'Bavaria'],
            ['Vivienne Sauer', 'Sturmgeschütz III Ausf. C', 'ATG', 'Bavaria'],
            ['Nana Walter', 'Sturmgeschütz III Ausf. D', 'ATG', 'Bavaria'],
            ['Marina Hoffman', 'Sturmgeschütz III Ausf. F', 'ATG', 'Bavaria'],
            ['Leah Rossiter', 'Sturmgeschütz III Ausf. G', 'ATG', 'Bavaria'],
            ['Stella Gerra', 'Sturmgeschütz III Prototype', 'ATG', 'Bavaria'],
            ['Mavis Fischer', 'Sturmgeschütz IV', 'ATG', 'Bavaria'],
            ['Ilona Hanks', 'Sturmpanther', 'ATG', 'Bavaria'],
            ['Cheri Arnold', 'Sturmpanzer Bar', 'SPG', 'Bavaria'],
            ['Cheri Arnold', 'Sturmtiger', 'ATG', 'Bavaria'],
            ['Daphne Davis', 'Super Hellcat', 'LAV', 'Freedonia'],
            ['Zoya Zhukova', 'T-10M', 'HT', 'Rossiya'],
            ['Elena Garinina', 'T-18 (Model 1930)', 'LT', 'Rossiya'],
            ['Dalia Kirillovna', 'T-18M', 'LT', 'Rossiya'],
            ['Eanna Isaakovna', 'T-26', 'LT', 'Rossiya'],
            ['Pauline Trepova', 'T-26B', 'LT', 'Rossiya'],
            ['Alra Semenovna', 'T-28 Medium Tank', 'MT', 'Rossiya'],
            ['Micah Roccaff', 'T-33 Scout Tank', 'LT', 'Rossiya'],
            ['Bella Zaitseva', 'T-34 Prototype', 'MT', 'Rossiya'],
            ['Chen Wenkui', 'T-34-2', 'MT', 'China'],
            ['Lydia Borisovna', 'T-34/100', 'MT', 'Rossiya'],
            ['Larissa Korovina', 'T-34/57', 'MT', 'Rossiya'],
            ['Maria Nisha', 'T-34/76', 'MT', 'Rossiya'],
            ['Natalia Borisova', 'T-34/85', 'MT', 'Rossiya'],
            ['Paulina Kapushkina', 'T-34M', 'MT', 'Rossiya'],
            ['Lisa Tognechkava', 'T-35-1', 'HT', 'Rossiya'],
            ['Faina Arkadiyevna', 'T-35A', 'HT', 'Rossiya'],
            ['Kelava Ignaziyeva', 'T-37 Scout Tank', 'LT', 'Rossiya'],
            ['Malina Hel', 'T-38 Scout Tank', 'LT', 'Rossiya'],
            ['Midya Yegorovna', 'T-40 Light Tank', 'LT', 'Rossiya'],
            ['Avdotiya Vlasovna', 'T-40/BM-8-24', 'SPG', 'Rossiya'],
            ['Evgeniya Kuznetsova', 'T-43 Medium Tank', 'MT', 'Rossiya'],
            ['Polina Pokrovka', 'T-44/100', 'MT', 'Rossiya'],
            ['Sawa Yermakovna', 'T-46', 'LT', 'Rossiya'],
            ['Laisa Ajolonva', 'T-50', 'LT', 'Rossiya'],
            ['Ekaterina Mikulchina', 'T-54 Medium Tank', 'MT', 'Rossiya'],
            ['Olivia Chicova', 'T-60 Light Tank', 'LT', 'Rossiya'],
            ['Susan Skaya', 'T-60/BM-8-24', 'SPG', 'Rossiya'],
            ['Natalia · Borisovna', 'T-62', 'MT', 'Rossiya'],
            ['Lena Tolubka', 'T-80 Light Tank', 'LT', 'Rossiya'],
            ['Shanaya Patrick', 'T1 Heavy Tank', 'HT', 'Freedonia'],
            ['Bernice Cameron', 'T1 Howitzer', 'SPG', 'Freedonia'],
            ['Perkins Angela', 'T17 Staghound', 'LAV', 'Freedonia'],
            ['Cheryl Klein', 'T17E1 Staghound (Mk-I)', 'LAV', 'Freedonia'],
            ['Sterling Paulson', 'T19 Howitzer', 'SPG', 'Freedonia'],
            ['Serra Jones', 'T24 Prototype', 'LT', 'Freedonia'],
            ['Delores Smith', 'T24E1', 'LT', 'Freedonia'],
            ['Nina Richards', 'T26 Tank', 'HT', 'Freedonia'],
            ['Lana Laurie', 'T26E5', 'HT', 'Freedonia'],
            ['Emily Randall', 'T28 Super Heavy Tank', 'ATG', 'Freedonia'],
            ['Judy O\'Brien', 'T29 Heavy Tank', 'HT', 'Freedonia'],
            ['Vashti Bradley', 'T29E3 Heavy Tank', 'HT', 'Freedonia'],
            ['Geluola·Weilianmusi', 'T32 Heavy Tank', 'HT', 'Freedonia'],
            ['Nikki Samuel', 'T34 Calliope', 'SPG', 'Freedonia'],
            ['Kerry Terence', 'T34E1 Calliope', 'SPG', 'Freedonia'],
            ['Othella Stevens', 'T37 Light Tank', 'LT', 'Freedonia'],
            ['Kelly Mohanderu', 'T40 Whizbang', 'SPG', 'Freedonia'],
            ['Eno Zamperini', 'T92 Self-Propelled Artillery', 'SPG', 'Freedonia'],
            ['Sylas Hubbard', 'TOG1', 'HT', 'Britannia'],
            ['Sylvia Harold', 'TOG2', 'HT', 'Britannia'],
            ['Rebecca Wagner', 'Tank Destroyer Test Type', 'ATG', 'Fusang'],
            ['Kacie Ram', 'Tetrarch (DD)', 'LT', 'Britannia'],
            ['Cherry Kelvin', 'Tetrarch Light Tank', 'LT', 'Britannia'],
            ['Sophie Arden', 'Tiger (Early Henschel)', 'HT', 'Bavaria'],
            ['Scarlet Goss', 'Tiger (Porsche)', 'HT', 'Bavaria'],
            ['Sally Hartman', 'Tiger Ausf. E', 'HT', 'Bavaria'],
            ['Lisa Hunt', 'Tiger II (Henschel)', 'HT', 'Bavaria'],
            ['Linda Werner', 'Tiger II (Porsche)', 'HT', 'Bavaria'],
            ['Rebecca Wagner', 'Type 5 Chi-Ri', 'MT', 'Fusang'],
            ['Chiha Akaneyae', 'Type 97 (Shinhoto)', 'MT', 'Fusang'],
            ['Peach Love', 'Type-61 Medium Tank', 'MT', 'Fusang'],
            ['Vera Farmiga', 'VK1602', 'LT', 'Bavaria'],
            ['Lomea Jeremy', 'Valentine', 'LT', 'Britannia'],
            ['Chloe Kate', 'Valentine III', 'LT', 'Britannia'],
            ['Zegna Chawla', 'Valentine VI', 'LT', 'Britannia'],
            ['Clary Judith', 'Valentine VIII', 'LT', 'Britannia'],
            ['Sadie Ironside', 'Valentine X', 'LT', 'Britannia'],
            ['Ivy Vickers', 'Vickers Mk.E', 'LT', 'Britannia'],
            ['Temanna Shetty', 'Vijayanta', 'MT', 'Britannia'],
            ['', 'WZ-120', 'MT', 'China'],
            ['Winny Arnold', 'Wespe SPG', 'SPG', 'Bavaria'],
            ['Ella Isayeva', 'Zis-30', 'ATG', 'Rossiya'],
            ['Flora Lucas', 'leFH18 B2', 'SPG', 'Bavaria'],
            ['Lihua Xu', 'm4a3 Rocket Launcher Type', 'MT', 'National Flag-08'],
            ['Greta Lehman', 'sIG-33', 'ATG', 'Bavaria']
        ];
    }
}
